### ISSUE TITLE
Are any of these of interest?

### ISSUE THREAD

**Issue by JeffreySarnoff** [jrevels/RealInterface.jl#1]
`cld`, `fld`
`isfinite`
`signbit`, `sign`, `copysign`, `flipsign`
`realmin`, `realmax`
`typemin`, `typemax`

**Comment by jrevels** [comment]
Thanks, I've just added `realmin`, `realmax`, `typemin`, `typemax`. I left off `signbit`, `sign`, `copysign`, `flipsign`, `cld`, and `fld`, since those pop out of the existing definitions, and `isfinite` was already there.
